---
- name: backup commands
  hosts: switches
  gather_facts: true
  connection: local
  tasks:
    - name: show run 
      ios_command:
        commands:
          - show run
        provider: 
          host: 1.1.1.1
          port: 22
          authorize: yes
          auth_pass: <password>
          username: admin
          password: <password>
      register: config

    - name: save output to /home/mark/backups 
      copy: 
         content: "{{ config.stdout[0] }}"
         dest: "/home/mark/backups/show_run_{{ inventory_hostname }}.txt"
...
