---

- name: dot1x timeout change for ports
  hosts: switches
  gather_facts: false
  connection: network_cli

  tasks:
    - name: dot1x timeout change 
      ios_config:
        lines: 
        - dot1x timeout tx-period 10
        parents: '{{ item }}'
      with_items:
        -  Interface GigabitEthernet1/0/2
        -  Interface GigabitEthernet1/0/3
        -  Interface GigabitEthernet1/0/4
        -  Interface GigabitEthernet1/0/5
        -  Interface GigabitEthernet1/0/6
        -  Interface GigabitEthernet1/0/7
        -  Interface GigabitEthernet1/0/8
        -  Interface GigabitEthernet1/0/9
        -  Interface GigabitEthernet1/0/10
        -  Interface GigabitEthernet1/0/11
        -  Interface GigabitEthernet1/0/12
      register: output

    - name: Save running-config
      ios_config:
        save_when: modified


    - name: print output
      debug:
        var: output
