---
datacenter:
  children:
    routers:
      hosts:
        192.168.1.16[1:5]:
      vars:
        testVar: 999
    switches:
      hosts:
        192.168.1.8[1:2]:
  vars:
    ansible_connection: network_cli
    ansible_network_os: ios
    ansible_user: cisco
    ansible_ssh_pass: cisco
    ansible_become_password: cisco
    ntp_servers:
      - 10.30.11.10
      - 10.20.11.10
